language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - cd frontend
  - yarn install
script:
  - yarn test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage